service: goatify-api-services
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production
    MONGODB_URI: ${env:MONGODB_URI}
    CLOUDINARY_CLOUD_NAME: ${env:CLOUDINARY_CLOUD_NAME}
    CLOUDINARY_API_KEY: ${env:CLOUDINARY_API_KEY}
    CLOUDINARY_API_SECRET: ${env:CLOUDINARY_API_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true

plugins:
  - serverless-offline
 

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 3000
  dotenv:
    path: .env

package:
  excludeDevDependencies: true
  include:
    - src/**
    - handler.js
    - package.json
  exclude:
    - .env
    - .git/**
    - .gitignore
    - README.md
    - test/**
    - coverage/**