service: goatify-api-services

frameworkVersion: '4'


provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production
  # environment:
  #   NODE_ENV: ${self:provider.stage}
  # iam:
  #   role:
  #     statements:
  #       - Effect: Allow
  #         Action:
  #           - logs:CreateLogGroup
  #           - logs:CreateLogStream
  #           - logs:PutLogEvents
  #         Resource: '*'

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
  dotenv:
    path: .env

package:
  excludeDevDependencies: true
  include:
    - src/**
    - handler.js
    - package.json